amber                   yes
parmfile                /home/rat/PycharmProjects/ML_models_NAMD/namd_benchmarks/enzyme/systems/mono_shell5/system.prmtop
coordinates             /home/rat/PycharmProjects/ML_models_NAMD/namd_benchmarks/enzyme/systems/mono_shell5/system.pdb
temperature             0
binaryoutput            no
outputname              probe
outputenergies          1
outputtiming            1
DCDfreq                 1
DCDfile                 pos.dcd
DCDUnitCell             no
forceDCDfreq            1
forceDCDfile            force.dcd
cutoff                  9.5
pairlistdist            11.5
switching               off
exclude                 scaled1-4
1-4scaling              0.833333
rigidbonds              none
timestep                0.5
firstTimestep           0
stepspercycle           1
fullElectFrequency      1
nonbondedfreq           1
langevin                off
QMForces                on
QMSoftware              fennol
QMExecPath              /home/rat/PycharmProjects/ML_models_NAMD/namd_benchmarks/enzyme/models/fennix_enzyme/mono_shell5/manifest.json
QMColumn                beta
qmParamPDB              /home/rat/PycharmProjects/ML_models_NAMD/namd_benchmarks/enzyme/systems/mono_shell5/qm.pdb
QMBaseDir               /tmp/namd_enzyme_qmmm
QMChargeMode            none
qmBondColumn            occ
QMSimsPerNode           1
qmReplaceAll            on
QMVdWParams             off
qmElecEmbed             off
QMSwitching             off
QMPointChargeScheme     none
QMMult                  1 1
QMCharge                1 0.00
run                     6
